apiVersion: v1
kind: Pod
metadata:
  name: nvidia-smi
  namespace: virtex
spec:
  nodeSelector:
    workLoad: server
  restartPolicy: OnFailure
  containers:
  - name: nvidia-smi
    image: nvidia/cuda:11.1-base
    args:
    - "nvidia-smi"
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
        nvidia.com/gpu: 1
      limits:
        memory: 1Gi
        cpu: 500m
        nvidia.com/gpu: 1