apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgateway
  namespace: virtex
  labels:
     app: pushgateway
spec:
  selector:
    matchLabels:
      app: pushgateway
  replicas: 1
  template:
    metadata:
       labels:
         app: pushgateway
    spec:
      containers:
       - name: pushgateway
         image: prom/pushgateway
         ports:
         - containerPort: 9091
      nodeSelector:
        workLoad: "client"
---
apiVersion: v1
kind: Service
metadata:
  name: pushgateway-svc
  namespace: virtex
spec:
  selector:
    app: pushgateway
  ports:
  - port: 9091
    protocol: TCP
    targetPort: 9091