apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtex
  namespace: virtex
  labels:
    app.kubernetes.io/name: virtex
    app.kubernetes.io/component: server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: virtex
      app.kubernetes.io/component: server
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: virtex
        app.kubernetes.io/component: server
    spec:
      nodeSelector:
        workLoad: server
      containers:
      - name: virtex-server
        image: 064721117073.dkr.ecr.us-east-2.amazonaws.com/virtex:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: 15Gi
            cpu: 8000m
          requests:
            memory: 15Gi
            cpu: 8000m
        ports:
          - name: virtex
            containerPort: 8081
        env:
          - name: TASK
            valueFrom:
              configMapKeyRef:
                name: virtex-server-config
                key: TASK
          - name: LOG_LEVEL
            valueFrom:
              configMapKeyRef:
                name: virtex-server-config
                key: LOG_LEVEL
          - name: VIRTEX_SERVICE_PORT
            valueFrom:
              configMapKeyRef:
                name: virtex-server-config
                key: VIRTEX_SERVICE_PORT
          - name: MAX_CONCURRENT_CONNECTIONS
            valueFrom:
              configMapKeyRef:
                name: virtex-server-config
                key: MAX_CONCURRENT_CONNECTIONS
          - name: NUM_VIRTEX_WORKERS
            valueFrom:
              configMapKeyRef:
                name: virtex-server-config
                key: NUM_VIRTEX_WORKERS
          - name: MAX_BATCH_SIZE
            valueFrom:
              configMapKeyRef:
                name: virtex-server-config
                key: MAX_BATCH_SIZE
          - name: MAX_TIME_ON_QUEUE
            valueFrom:
              configMapKeyRef:
                name: virtex-server-config
                key: MAX_TIME_ON_QUEUE
          - name: METRICS_INTERVAL
            valueFrom:
              configMapKeyRef:
                name: virtex-server-config
                key: METRICS_INTERVAL
          - name: MAX_SEQUENCE_LENGTH
            valueFrom:
              configMapKeyRef:
                name: virtex-server-config
                key: MAX_SEQUENCE_LENGTH
---
apiVersion: v1
kind: Service
metadata:
  name: virtex
  namespace: virtex
  labels:
    app.kubernetes.io/name: virtex
    app.kubernetes.io/component: server
spec:
  ports:
  - name: virtex
    port: 8081
    targetPort: virtex
  selector:
    app.kubernetes.io/name: virtex
    app.kubernetes.io/component: server