apiVersion: v1
kind: Service
metadata:
  name: virtex
  labels:
    app.kubernetes.io/name: virtex
    app.kubernetes.io/component: server
spec:
  ports:
    - name: virtex
      port: 8081
      targetPort: virtex
  selector:
    app.kubernetes.io/name: virtex
    app.kubernetes.io/component: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtex
  labels:
    app.kubernetes.io/name: virtex
    app.kubernetes.io/component: server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: virtex
      app.kubernetes.io/component: server
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 4
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: virtex
        app.kubernetes.io/component: server
    spec:
      containers:
      - name: virtex
        image: 064721117073.dkr.ecr.us-east-2.amazonaws.com/virtex:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: 2Gi
            cpu: 1000m
          requests:
            memory: 2Gi
            cpu: 1000m
        env:
          - name: TASK
            valueFrom:
              configMapKeyRef:
                name: virtex-load-test-config
                key: TASK
          - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: virtex-load-test-config
                  key: LOG_LEVEL
          - name: VIRTEX_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: virtex-load-test-config
                  key: VIRTEX_SERVICE_PORT
          - name: MAX_CONCURRENT_CONNECTIONS
              valueFrom:
                configMapKeyRef:
                  name: virtex-load-test-config
                  key: MAX_CONCURRENT_CONNECTIONS
          - name: NUM_VIRTEX_WORKERS
              valueFrom:
                configMapKeyRef:
                  name: virtex-load-test-config
                  key: NUM_VIRTEX_WORKERS
          - name: MAX_BATCH_SIZE
              valueFrom:
                configMapKeyRef:
                  name: virtex-load-test-config
                  key: MAX_BATCH_SIZE
          - name: MAX_TIME_ON_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: virtex-load-test-config
                  key: MAX_TIME_ON_QUEUE
          - name: METRICS_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: virtex-load-test-config
                  key: METRICS_INTERVAL
          - name: MAX_SEQUENCE_LENGTH
              valueFrom:
                configMapKeyRef:
                  name: virtex-load-test-config
                  key: MAX_SEQUENCE_LENGTH
          - name: NUM_INFERENCES
              valueFrom:
                configMapKeyRef:
                  name: virtex-load-test-config
                  key: NUM_INFERENCES
          - name: CLIENT_REQUESTS_PER_SECOND
              valueFrom:
                configMapKeyRef:
                  name: virtex-load-test-config
                  key: CLIENT_REQUESTS_PER_SECOND
          - name: REQUEST_BATCH_SIZE
              valueFrom:
                configMapKeyRef:
                  name: virtex-load-test-config
                  key: REQUEST_BATCH_SIZE
          - name: CONTENT_LENGTH
              valueFrom:
                configMapKeyRef:
                  name: virtex-load-test-config
                  key: CONTENT_LENGTH
        ports:
        - name: virtex
          containerPort: 8081