apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtex-server
  namespace: virtex
  labels:
     app: virtex-server
spec:
  selector:
    matchLabels:
      app: virtex-server
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 2
  template:
    metadata:
      labels:
        app: virtex-server
    spec:
      nodeSelector:
        workLoad: server
      # restartPolicy: Always
      containers:
      - name: virtex-server
        image: virtexlabs/virtex-benchmark:latest
        imagePullPolicy: Always
        resources:
          requests:
            # memory: 11Gi
            # cpu: 5500m
            # memory: 50Gi
            # cpu: 7500m
            memory: 50Gi
            cpu: 7000m
            nvidia.com/gpu: 1
          limits:
            # memory: 11Gi
            # cpu: 5500m
            # memory: 55Gi
            # cpu: 7500m
            memory: 50Gi
            cpu: 7000m
            nvidia.com/gpu: 1
        ports:
        - containerPort: 8081
        envFrom:
        - configMapRef:
            name: base-cfg
        - configMapRef:
            name: bert-server-cfg
---
apiVersion: v1
kind: Service
metadata:
  name: virtex-svc
  namespace: virtex
spec:
  selector:
    app: virtex-server
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081