apiVersion: batch/v1
kind: Job
metadata:
  name: virtex-load-test
  namespace: virtex
  labels:
    app: virtex-client
spec:
  parallelism: 4
  completions: 4
  template:
    spec:
      nodeSelector:
        workLoad: client
      restartPolicy: Never
      containers:
      - name: virtex-client
        image: 064721117073.dkr.ecr.us-east-2.amazonaws.com/virtex:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: 6Gi
            cpu: 1500m
          requests:
            memory: 6Gi
            cpu: 1500m
        envFrom:
        - configMapRef:
            name: base-cfg
        - configMapRef:
            name: bert-client-cfg