apiVersion: batch/v1
kind: Job
metadata:
  name: virtex-load-test
  namespace: virtex
  labels:
    app: virtex-client
spec:
  parallelism: 1
  completions: 1
  template:
    spec:
      nodeSelector:
        workLoad: client
      restartPolicy: Never
      containers:
      - name: virtex-client
        image: virtexlabs/virtex-benchmark:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: 3Gi
            cpu: 1500m
          requests:
            memory: 3Gi
            cpu: 1500m
        envFrom:
          - configMapRef:
              name: base-cfg
          - configMapRef:
              name: echo-client-cfg