apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: virtex-01
  region: us-east-2
  version: 1.19

nodeGroups:
  - name: client-node-group
    instanceType: m5.large
    desiredCapacity: 2
    volumeSize: 80
  - name: server-node-group
    instanceType: m5.xlarge
    desiredCapacity: 2
    volumeSize: 100