apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: virtex-perf
  region: us-east-2
  version: "1.19"
nodeGroups:
  - name: client-node-group
    privateNetworking: true
    instanceType: c5d.2xlarge
    # 8vcpu / 16GB / 1 x 200 NVMe SSD / $0.384/hr
    desiredCapacity: 2
    volumeSize: 100
    labels:
      workLoad: client
  - name: server-node-group
    privateNetworking: true
    instanceType: c5d.12xlarge
    # 48vcpu / 96GB / 2 x 900 NVMe SSD / $2.304/hr
    desiredCapacity: 2
    volumeSize: 200
    labels:
      workLoad: server